# -*- coding: utf-8 -*-
"""DevSecOps SecurityMesh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GPq1iIfaRYatsQ_LNHd4yy0td8f7byG

### Set up NVIDIA API Key
To use the NVIDIA API, you'll need to securely store your API key and then use it to initialize any NVIDIA API clients or SDKs.
"""

# It's recommended to store sensitive information like API keys securely.
# In Colab, you can use the Secrets Manager (the '🔑' icon in the left panel).
# Let's assume you've stored your NVIDIA API key there under the name 'NVIDIA_API_KEY'.

from google.colab import userdata

# Retrieve the API key from Colab's Secrets Manager
NVIDIA_API_KEY = userdata.get('NVIDIA_API_KEY')

# --- Placeholder for NVIDIA API interaction ---
# Replace this with actual code to initialize and use the NVIDIA API.
# For example, if there's an NVIDIA SDK or client library:
# from nvidia_api_sdk import NVIDIAClient
# client = NVIDIAClient(api_key=NVIDIA_API_KEY)

print("NVIDIA API key loaded. You can now use it to initialize your agent or API client.")
# Example: If you were building an agent, you might pass this key to its constructor.
# my_nvidia_agent = MyAgent(nvidia_api_key=NVIDIA_API_KEY)
# response = client.some_api_call()
# print(response)

"""## Code Security Module: Python Static Analysis

This section will focus on scanning a Python file for common vulnerabilities and secrets using static analysis tools. We'll use `bandit` as a primary tool for security analysis.

### 1. Create a Sample Python File

First, let's create a dummy Python file that we can scan. This file will include some common patterns that security linters might flag.
"""

sample_python_code = '''
import os
import subprocess

def execute_command(command):
    # CWE-78: Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')
    subprocess.call(f'echo {command}', shell=True)

def hardcoded_password_check():
    # CWE-798: Use of Hard-coded Credentials
    password = "my_super_secret_password"
    print(f"Checking password: {password}")

def use_eval(user_input):
    # CWE-94: Improper Control of Generation of Code ('Code Injection')
    eval(user_input)

if __name__ == "__main__":
    execute_command("ls -la")
    hardcoded_password_check()
    use_eval("print('Hello from eval!')")
'''

file_name = "vulnerable_app.py"
with open(file_name, "w") as f:
    f.write(sample_python_code)

print(f"Created '{file_name}' with sample vulnerable code.")

"""### 2. Install Bandit

`bandit` is a tool designed to find common security issues in Python code. It is an open-source security linter provided by OpenStack Security.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install bandit

"""### 3. Run Bandit Scan

Now, let's run `bandit` on our sample Python file. We'll capture the output to analyze the findings.
"""

import subprocess

print(f"Scanning '{file_name}' with Bandit...")

# Run bandit as a subprocess and capture its output
# -r: recursive (scan directory)
# -f json: output format as JSON (for easier parsing)
# -q: quiet (suppress progress messages)
# --force-include: include the specified file even if it's not a .py file (useful if the file extension is custom)

result = subprocess.run(
    ['bandit', '-r', file_name, '-f', 'json', '-q'],
    capture_output=True,
    text=True,
    check=False # Do not raise an exception for non-zero exit codes (e.g., if vulnerabilities are found)
)

# Print the raw JSON output for inspection
# In a real agent, you would parse this JSON to extract findings
print("\nBandit Scan Results (JSON):")
print(result.stdout)

# Optionally, print stderr if there were any issues with bandit itself
if result.stderr:
    print("\nBandit Errors (stderr):")
    print(result.stderr)

# A more user-friendly summary might involve parsing the JSON output
import json

try:
    scan_data = json.loads(result.stdout)
    print("\nSummary of Bandit Findings:")
    if scan_data and 'results' in scan_data:
        if scan_data['results']:
            for finding in scan_data['results']:
                print(f"  Issue: {finding['issue_text']}")
                print(f"    Severity: {finding['issue_severity']}, Confidence: {finding['issue_confidence']}")
                print(f"    File: {finding['filename']}, Line: {finding['line_number']}")
                print(f"    Code: {finding['code']}")
                print("    ---")
        else:
            print("  No security issues found by Bandit.")
    else:
        print("  Could not parse Bandit results or no 'results' key found.")
except json.JSONDecodeError:
    print("  Error decoding JSON output from Bandit.")
    print("  Raw output might not be valid JSON.")

"""### 4. Remediate Vulnerabilities

Now, let's create a corrected version of the `vulnerable_app.py` file, addressing the issues Bandit found. We'll:

*   Use `subprocess.run` without `shell=True` and pass commands as a list for OS command execution.
*   Remove the hardcoded password and suggest using environment variables or a secrets management system.
*   Replace `eval()` with `ast.literal_eval()` for safe evaluation of Python literals.
"""

remediated_python_code = '''
import os
import subprocess
import ast # For safe evaluation

def execute_command_safe(command_parts):
    # CWE-78: Proper Neutralization of Special Elements used in an OS Command ('OS Command Injection')
    # Using subprocess.run with command as a list, and without shell=True
    try:
        # Example: command_parts might be ['ls', '-la', '/tmp']
        result = subprocess.run(command_parts, check=True, capture_output=True, text=True)
        print("Command output:\n", result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Command failed with error: {e.stderr}")

def get_password():
    # CWE-798: Avoiding Use of Hard-coded Credentials
    # Fetch password from environment variable or a secure secrets manager
    password = os.getenv("APP_PASSWORD", "default_fallback_password") # Fallback for demonstration
    if password == "default_fallback_password":
        print("Warning: Using a fallback password. Consider setting APP_PASSWORD environment variable.")
    return password

def safe_evaluate(user_input_string):
    # CWE-94: Safer Control of Generation of Code
    # Using ast.literal_eval for safe evaluation of Python literals
    try:
        return ast.literal_eval(user_input_string)
    except (ValueError, SyntaxError) as e:
        print(f"Error evaluating input safely: {e}")
        return None

if __name__ == "__main__":
    print("\n--- Executing safe command ---")
    execute_command_safe(["ls", "-la", "."])

    print("\n--- Checking password ---")
    app_password = get_password()
    print(f"Retrieved password (first 5 chars): {app_password[:5]}...")

    print("\n--- Safe evaluation example ---")
    # This will work safely
    print("Safe eval result:", safe_evaluate("[1, 2, {'a': 3}]"))
    # This will fail safely
    print("Unsafe eval attempt result:", safe_evaluate("os.system('rm -rf /')"))
'''

remediated_file_name = "remediated_app.py"
with open(remediated_file_name, "w") as f:
    f.write(remediated_python_code)

print(f"Created '{remediated_file_name}' with remediated code.")

"""### 5. Re-run Bandit Scan on Remediated File

Let's scan the `remediated_app.py` file to see if our fixes have successfully addressed the security issues.
"""

import subprocess
import json

print(f"Scanning '{remediated_file_name}' with Bandit...")

result_remediated = subprocess.run(
    ['bandit', '-r', remediated_file_name, '-f', 'json', '-q'],
    capture_output=True,
    text=True,
    check=False
)

print("\nBandit Scan Results (JSON) for Remediated File:")
print(result_remediated.stdout)

if result_remediated.stderr:
    print("\nBandit Errors (stderr) for Remediated File:")
    print(result_remediated.stderr)

try:
    scan_data_remediated = json.loads(result_remediated.stdout)
    print("\nSummary of Bandit Findings for Remediated File:")
    if scan_data_remediated and 'results' in scan_data_remediated:
        if scan_data_remediated['results']:
            for finding in scan_data_remediated['results']:
                print(f"  Issue: {finding['issue_text']}")
                print(f"    Severity: {finding['issue_severity']}, Confidence: {finding['issue_confidence']}")
                print(f"    File: {finding['filename']}, Line: {finding['line_number']}")
                print(f"    Code: {finding['code']}")
                print("    ---")
        else:
            print("  No security issues found by Bandit in the remediated file!")
    else:
        print("  Could not parse Bandit results or no 'results' key found for remediated file.")
except json.JSONDecodeError:
    print("  Error decoding JSON output from Bandit for remediated file.")
    print("  Raw output might not be valid JSON.")

"""## Container Security Module: Docker Image Vulnerability Scanning

This section will demonstrate how to scan a Docker image for known vulnerabilities. We'll use `Grype`, a powerful open-source vulnerability scanner for container images and filesystems.

### 1. Set up Docker Environment

To build and scan Docker images within Colab, we need to ensure Docker is running and accessible. We'll install `docker-py` to interact with the Docker daemon programmatically, and use `docker` CLI commands.
"""

# Install the Docker SDK for Python
# %pip install docker

# Start Docker service (often already running in Colab environments, but good to ensure)
# This command might not be strictly necessary or may show a message if Docker is already up.
# It's more common to run `sudo service docker start` in a regular Linux environment.
# In Colab, the Docker daemon is usually managed by the environment itself.

# Verify Docker is running
# import docker

# try:
#     client = docker.from_env()
#     client.ping()
#     print("Docker daemon is running.")
# except Exception as e:
#     print(f"Error connecting to Docker daemon: {e}")
#     print("Please ensure Docker is installed and running correctly.")
print("Skipping Docker daemon setup as it's not supported in this Colab environment for local image builds.")

"""### 2. Create a Sample Vulnerable Dockerfile

We'll create a simple Dockerfile based on an older, known-vulnerable base image to ensure `Grype` has something to find.
"""

dockerfile_content = '''
# Using an old and vulnerable Debian base image (Debian 9 Stretch)
FROM debian:stretch-slim

LABEL maintainer="DevSecOps Guardian AI"

# Install some common packages, including potentially vulnerable ones
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    wget \
    git \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Copy a simple app (e.g., our vulnerable Python app from before)
COPY vulnerable_app.py /app/vulnerable_app.py
WORKDIR /app

# Expose a port (even if not used, common for web apps)
EXPOSE 8080

CMD ["python3", "vulnerable_app.py"]
'''

dockerfile_name = "Dockerfile.vulnerable"
with open(dockerfile_name, "w") as f:
    f.write(dockerfile_content)

print(f"Created '{dockerfile_name}' with sample vulnerable Dockerfile content.")

"""### 3. Build the Docker Image

Now, let's build the Docker image from our vulnerable Dockerfile. We'll tag it so we can easily reference it later.
"""

# import docker

# client = docker.from_env()
# image_name = "vulnerable-python-app:latest"

# print(f"Building Docker image '{image_name}' from '{dockerfile_name}'...")

# try:
#     # Ensure the vulnerable_app.py is in the current directory
#     # The build context is '.' so Docker can find vulnerable_app.py
#     image, build_logs = client.images.build(
#         path=".",
#         dockerfile=dockerfile_name,
#         tag=image_name,
#         rm=True # Remove intermediate containers after a successful build
#     )
#     print(f"Successfully built image: {image.tags[0]}")

#     # Print build logs if needed (useful for debugging)
#     # for line in build_logs:
#     #     if 'stream' in line:
#     #         print(line['stream'], end='')

# except docker.errors.BuildError as e:
#     print(f"Error building Docker image: {e}")
#     # Print build logs from error for more details
#     for line in e.build_log:
#         if 'stream' in line:
#         print(line['stream'], end='')
# except Exception as e:
#     print(f"An unexpected error occurred: {e}")
print("Skipping Docker image build due to environment limitations. We will proceed with scanning a remote image.")

"""### 4. Install Grype

`Grype` is a command-line tool for scanning container images and filesystems for vulnerabilities. We will install it via `pip` (if available as a package) or by downloading its binary.
"""

# Grype is typically installed by downloading its binary.
# We'll use wget to download and install it in /usr/local/bin

import os
import subprocess

grype_install_dir = "/usr/local/bin"
grype_path = os.path.join(grype_install_dir, "grype")

if not os.path.exists(grype_path):
    print("Installing Grype...")
    install_command = [
        "curl", "-sLf",
        "https://raw.githubusercontent.com/anchore/grype/main/install.sh",
        "|", "sh", "-s", "--", "-b", grype_install_dir
    ]
    # Using subprocess.run with shell=True for the pipe, but carefully constructed.
    # In a production environment, direct download and move is safer to avoid shell injection.
    try:
        subprocess.run(
            " ".join(install_command),
            shell=True,
            check=True,
            capture_output=True,
            text=True
        )
        print("Grype installed successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error installing Grype: {e.stderr}")
    except Exception as e:
        print(f"An unexpected error occurred during Grype installation: {e}")
else:
    print("Grype is already installed.")

# Verify Grype installation
try:
    version_output = subprocess.run([grype_path, "version"], capture_output=True, text=True, check=True)
    print("\nGrype Version:")
    print(version_output.stdout)
except Exception as e:
    print(f"Could not verify Grype installation: {e}")

"""### 5. Run Grype Scan on a Remote Docker Image

Since we cannot build local Docker images in Colab, we will use `Grype` to scan a publicly available vulnerable Docker image directly from a registry (e.g., Docker Hub). This demonstrates the image vulnerability scanning capability without needing a local Docker daemon.

We will use `vulnerables/web-dvwa` as our target image, which is intentionally designed to be vulnerable.
"""

import subprocess
import json
import os

grype_path = os.path.join("/usr/local/bin", "grype") # Ensure correct path to grype

# Define the remote vulnerable image to scan
remote_image_name = "vulnerables/web-dvwa:latest"

print(f"Scanning remote Docker image '{remote_image_name}' with Grype...")

try:
    # Grype can directly pull and scan remote images
    grype_command = [grype_path, remote_image_name, "--scope", "all-layers", "-o", "json"]
    scan_result = subprocess.run(
        grype_command,
        capture_output=True,
        text=True,
        check=False # Do not raise an exception if vulnerabilities are found
    )

    # Print raw JSON output
    print("\nGrype Scan Results (JSON):")
    print(scan_result.stdout)

    if scan_result.stderr:
        print("\nGrype Errors (stderr):")
        print(scan_result.stderr)

    # Parse and summarize results
    try:
        grype_data = json.loads(scan_result.stdout)
        print("\nSummary of Grype Findings:")
        if grype_data and 'matches' in grype_data:
            vulnerability_count = len(grype_data['matches'])
            if vulnerability_count > 0:
                print(f"  Found {vulnerability_count} vulnerabilities.")
                # Example: Print top 5 vulnerabilities by severity
                sorted_matches = sorted(
                    grype_data['matches'],
                    key=lambda x: x['vulnerability']['severity'],
                    reverse=True
                )
                print("  Top vulnerabilities:")
                for i, match in enumerate(sorted_matches[:5]):
                    vuln = match['vulnerability']
                    artifact = match['artifact']
                    print(f"    {i+1}. {vuln['id']} ({vuln['severity']}) - {artifact['name']}@{artifact['version']}")
                    if 'fix' in vuln and vuln['fix']['state'] != 'not-fixed':
                        print(f"       Fix: {vuln['fix']['state']}")
                    print(f"       Description: {vuln.get('description', 'N/A')[:100]}...") # Truncate description
                    print("      ---")
            else:
                print("  No vulnerabilities found by Grype!")
        else:
            print("  Could not parse Grype results or no 'matches' key found.")
    except json.JSONDecodeError:
        print("  Error decoding JSON output from Grype.")
        print("  Raw output might not be valid JSON.")

except Exception as e:
    print(f"An error occurred during Grype scanning: {e}")

"""## Dependency Security Module: Python Dependency Scanning

This section will focus on scanning Python project dependencies for known vulnerabilities. We'll use `pip-audit` for this purpose, which checks against public vulnerability databases.

### 1. Create a Sample `requirements.txt`

First, let's create a `requirements.txt` file that includes some known-vulnerable Python packages. This will allow `pip-audit` to find issues.
"""

requirements_content = '''
requests==2.21.0  # Known vulnerability in older versions
numpy==1.22.0    # Known vulnerability in older versions
flask==1.0.2     # Older version, might have minor issues
'''

requirements_file = "requirements.txt"
with open(requirements_file, "w") as f:
    f.write(requirements_content)

print(f"Created '{requirements_file}' with sample dependencies.")

# Commented out IPython magic to ensure Python compatibility.
print(f"Installing dependencies from '{requirements_file}'...")
# %pip install -r {requirements_file}
print("Dependencies installed.")

"""### 2. Install `pip-audit`

`pip-audit` is a powerful tool for auditing Python environments and requirements files for known vulnerabilities.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pip-audit

"""### 3. Run `pip-audit` Scan

Now, let's run `pip-audit` on our `requirements.txt` file to identify any vulnerable dependencies.
"""

import subprocess
import json

print("Scanning currently installed packages for vulnerabilities with pip-audit...")

try:
    # Run pip-audit on the currently installed packages (no -r flag)
    # We assume the packages from requirements.txt have already been installed.
    pip_audit_command = ['pip-audit', '--format', 'json']
    audit_result = subprocess.run(
        pip_audit_command,
        capture_output=True,
        text=True,
        check=False # Allow non-zero exit code if vulnerabilities are found
    )

    # Print raw JSON output
    print("\npip-audit Scan Results (JSON):")
    print(audit_result.stdout)

    if audit_result.stderr:
        print("\npip-audit Errors (stderr):")
        print(audit_result.stderr)

    # Parse and summarize results
    try:
        audit_data = json.loads(audit_result.stdout)
        print("\nSummary of pip-audit Findings:")
        vulnerable_packages_found = 0
        # pip-audit's output format can vary. Try to parse based on 'dependencies' key.
        if 'dependencies' in audit_data and audit_data['dependencies']:
            for dep_info in audit_data['dependencies']:
                if 'vulns' in dep_info and isinstance(dep_info['vulns'], list) and dep_info['vulns']:
                    vulnerable_packages_found += 1
                    package_name = dep_info.get('name', 'Unknown')
                    package_version = dep_info.get('version', 'Unknown')

                    print(f"  - Package: {package_name}=={package_version}")
                    for vuln in dep_info['vulns']:
                        if isinstance(vuln, dict):
                            print(f"    Vulnerability ID: {vuln.get('id', 'N/A')}")
                            description = vuln.get('details', 'No description available')
                            print(f"    Description: {description[:150]}...")
                            if 'fix_versions' in vuln and vuln['fix_versions']:
                                print(f"    Fix versions: {', '.join(vuln['fix_versions'])}")
                            else:
                                print("    No specific fix versions mentioned.")
                            print("    --- ")
                        else:
                            print(f"    Non-dictionary vulnerability item found: {vuln}")
            if vulnerable_packages_found == 0:
                print("  No vulnerable packages found by pip-audit.")
            else:
                print(f"  Found a total of {vulnerable_packages_found} packages with vulnerabilities.")
        else:
            print("  No vulnerable packages found by pip-audit.")
    except json.JSONDecodeError:
        print("  Error decoding JSON output from pip-audit.")
        print("  Raw output might not be valid JSON.")

except Exception as e:
    print(f"An error occurred during pip-audit scanning: {e}")

"""## Secret Management

Handling sensitive information like API keys, database credentials, and other secrets is paramount in secure application development. Hardcoding secrets directly into code is a major security risk, as demonstrated by the `hardcoded_password_check` vulnerability found by Bandit.

This section will explore better practices for managing secrets, focusing on:

1.  **Environment Variables**: A common and straightforward method for passing secrets to applications.
2.  **Colab's Secrets Manager**: Leveraging Colab's built-in feature for secure secret storage.
3.  **Introduction to more advanced Secret Management Systems (Optional)**: Briefly discuss dedicated tools like HashiCorp Vault or AWS Secrets Manager for production environments.

### 1. Using Environment Variables for Secrets

Environment variables provide a way to inject configuration, including secrets, into an application without embedding them in the codebase. This is a widely adopted practice for development and deployment.

Let's simulate setting an environment variable and then accessing it within Python.
"""

import os

# Simulate setting an environment variable (in a real scenario, this would be set outside the script)
# For demonstration in Colab, we can set it directly.
# IMPORTANT: Do not hardcode actual secrets here in a real application or share publicly!
os.environ['MY_API_KEY'] = 'super_secret_api_key_123'
os.environ['DATABASE_PASSWORD'] = 'db_pass_secure'

print("Environment variables 'MY_API_KEY' and 'DATABASE_PASSWORD' simulated.")

# Now, retrieve the environment variable
api_key = os.getenv('MY_API_KEY')
db_password = os.getenv('DATABASE_PASSWORD')

print(f"\nRetrieved API Key: {api_key[:5]}... (first 5 characters)")
print(f"Retrieved Database Password: {db_password[:5]}... (first 5 characters)")

# Demonstrate handling missing environment variables
non_existent_secret = os.getenv('NON_EXISTENT_SECRET', 'default_value')
print(f"Non-existent secret (with default): {non_existent_secret}")

del os.environ['MY_API_KEY']
del os.environ['DATABASE_PASSWORD']
print("Simulated environment variables cleared.")

"""### 2. Using Colab's Secrets Manager

Colab provides a built-in Secrets Manager (accessible via the 🔑 icon on the left-hand panel) to securely store and retrieve sensitive information like API keys. Secrets stored here are not saved with your notebook content and are managed separately, offering a more secure alternative to environment variables that might be accidentally committed to source control or hardcoded.

Let's re-examine how to access a secret named `NVIDIA_API_KEY` (or any other secret you might have stored there) using `google.colab.userdata`.
"""

from google.colab import userdata

# Assuming you have a secret named 'NVIDIA_API_KEY' stored in Colab's Secrets Manager.
# If you don't, you can add one now by clicking the '🔑' icon.

# Attempt to retrieve the secret
try:
    colab_api_key = userdata.get('NVIDIA_API_KEY')
    if colab_api_key:
        print(f"Successfully retrieved 'NVIDIA_API_KEY' from Colab Secrets (first 5 chars): {colab_api_key[:5]}...")
    else:
        print("Secret 'NVIDIA_API_KEY' not found in Colab Secrets Manager. Please add it.")
except Exception as e:
    print(f"An error occurred while retrieving secret: {e}")

# Example with a non-existent secret (without a fallback, will return None)
non_existent_colab_secret = userdata.get('MY_NON_EXISTENT_COLAB_SECRET')
print(f"\nAttempt to retrieve non-existent Colab secret: {non_existent_colab_secret} (Expected: None)")

# Example with a default fallback value if the secret is not found
fallback_secret = userdata.get('ANOTHER_SECRET', 'colab_fallback_value')
print(f"Attempt to retrieve another secret (with fallback): {fallback_secret}")

print("\nThis method securely retrieves secrets without exposing them in your code or notebook output.")

"""### 3. Introduction to Advanced Secret Management Systems

While environment variables and Colab's Secrets Manager are excellent for development and specific use cases, larger applications, especially in production, often leverage dedicated Secret Management Systems. These systems offer advanced features like:

*   **Centralized Storage**: All secrets in one secure location.
*   **Access Control**: Granular permissions to define who (or what application) can access which secret.
*   **Auditing**: Tracking who accessed what secret and when.
*   **Rotation**: Automated secret rotation to minimize risk.
*   **Encryption**: Secrets are encrypted at rest and often in transit.

Examples of such systems include:

*   **HashiCorp Vault**: A popular open-source tool for managing secrets, offering a wide range of features and integrations.
*   **AWS Secrets Manager / Azure Key Vault / Google Cloud Secret Manager**: Cloud-native solutions that integrate seamlessly with their respective cloud ecosystems.
*   **Kubernetes Secrets**: While not a full-fledged secret manager, Kubernetes offers its own mechanism for handling secrets within containerized applications.

Understanding these concepts is crucial for building secure, scalable applications.

## Next Steps in Security Exploration

We've covered Static Code Analysis, Container Image Vulnerability Scanning, Dependency Scanning, and Secret Management.

What other security aspects would you like to explore next? We could delve into:

*   **Security Testing**: Unit tests, integration tests, or penetration testing concepts.
*   **CI/CD Integration**: How these security tools fit into an automated development pipeline.
*   **Input Validation/Output Encoding**: Preventing common web vulnerabilities like XSS and SQL Injection.
*   **Authentication and Authorization**: Implementing secure user access.

Or perhaps a deeper dive into any of the topics we've already touched upon?

## Input Validation and Output Encoding

**Input Validation** and **Output Encoding** are fundamental security practices to protect applications from various attacks, most notably Injection attacks (like SQL Injection, Command Injection) and Cross-Site Scripting (XSS).

*   **Input Validation**: Ensures that any data received by the application (e.g., from users, APIs, files) conforms to expected formats, types, and ranges before it is processed. This prevents malicious or malformed data from causing unintended behavior or security breaches.

*   **Output Encoding (or Escaping)**: Converts untrusted data into a safe form before it is rendered or transmitted to another system. This ensures that the data is treated as data, not as executable code or commands, thereby preventing code injection vulnerabilities.

Let's explore some examples.

## Threat Modeling: Identifying and Mitigating Security Risks

**Threat Modeling** is a structured approach to identify, quantify, and address security risks within a system, application, or process. It helps developers and security professionals understand where the system might be vulnerable and what measures can be taken to protect it.

The core idea is to think like an attacker to proactively discover potential weaknesses before they can be exploited. It's often performed early in the software development lifecycle (SDLC), aligning with the "shift left" security principle.

### Why is Threat Modeling Important?

*   **Proactive Security**: Identifies design flaws and vulnerabilities before code is even written or deployed.
*   **Risk Prioritization**: Helps prioritize security efforts by focusing on the most critical threats.
*   **Cost-Effective**: Fixing security issues in the design phase is significantly cheaper than fixing them in production.
*   **Compliance**: Supports compliance with various security standards and regulations.
*   **Better Communication**: Provides a common language for discussing security concerns among stakeholders.

### Common Threat Modeling Methodologies

Several methodologies exist, each with its own focus:

*   **STRIDE**: Developed by Microsoft, STRIDE categorizes threats into six types:
    *   **S**poofing (of user identity)
    *   **T**ampering (of data)
    *   **R**epudiation (of actions)
    *   **I**nformation Disclosure (privacy breach or data leak)
    *   **D**enial of Service (DoS)
    *   **E**levation of Privilege
*   **DREAD**: Often used with STRIDE to rate the severity of identified threats based on:
    *   **D**amage
    *   **R**eproducibility
    *   **E**xploitability
    *   **A**ffected users
    *   **D**iscoverability
*   **PASTA (Process for Attack Simulation and Threat Analysis)**: A seven-step, risk-centric methodology that helps align business objectives with technical requirements.
*   **Attack Trees**: A hierarchical diagram that breaks down a high-level attack goal into more specific sub-goals and attack vectors.

For this exercise, we'll use a simplified approach inspired by STRIDE to identify potential threats for a basic web application scenario.

### A Simple Threat Modeling Process

Here's a simplified process we can follow:

1.  **Define the System/Application**: Clearly understand what we are modeling.
2.  **Identify Assets**: What are the valuable things we need to protect?
3.  **Identify Trust Boundaries and Data Flows**: Where does data move, and where do trust levels change?
4.  **Identify Threats (using STRIDE or similar)**: Brainstorm potential attacks against the assets and data flows.
5.  **Identify Vulnerabilities**: What weaknesses in the system could allow these threats to materialize?
6.  **Determine Countermeasures**: How can we mitigate or eliminate these threats and vulnerabilities?
7.  **Verify Countermeasures**: Ensure the implemented countermeasures are effective (e.g., through testing).

Let's apply this to a hypothetical simple user registration and login web application.
"""

# This is a conceptual exercise. We will use print statements to outline the steps and findings.

print("--- Starting Simple Web Application Threat Model ---")

# 1. Define the System/Application
print("\n1. System/Application Definition:")
print("   A basic web application that allows users to register, log in, and view their personal profile.")
print("   Components: Web Browser (Client), Web Server (Backend), Database (User Data).")

# 2. Identify Assets
print("\n2. Identified Assets:")
assets = [
    "User PII (Personally Identifiable Information) - e.g., email, password hash, name",
    "User Session Tokens",
    "Application Code and Configuration",
    "Database Integrity and Availability",
    "Server Resources (CPU, Memory, Bandwidth)"
]
for asset in assets:
    print(f"   - {asset}")

# 3. Identify Trust Boundaries and Data Flows
print("\n3. Trust Boundaries and Data Flows:")
print("   - Client (Browser) <---- (HTTPS) ----> Web Server (Authenticated Users)")
print("   - Web Server <---- (Internal API/DB Connection) ----> Database")
print("   - Trust Boundary: Between Client and Web Server, and between Web Server and Database.")

# 4. Identify Threats (STRIDE)
print("\n4. Identified Threats (using STRIDE):")
threats = {
    "Spoofing": [
        "User identity spoofing (e.g., session hijacking, brute-force login)",
        "Web Server spoofing (e.g., phishing, fake server)"
    ],
    "Tampering": [
        "Data tampering in transit (e.g., modifying requests/responses)",
        "Data tampering at rest (e.g., modifying database records)",
        "Application code tampering"
    ],
    "Repudiation": [
        "User denies performing an action (e.g., making a purchase, posting content)"
    ],
    "Information Disclosure": [
        "Exposure of user PII from database breach",
        "Exposure of session tokens",
        "Exposure of sensitive error messages/stack traces",
        "Exposure of API keys/credentials"
    ],
    "Denial of Service (DoS)": [
        "Overloading server with traffic (DDoS)",
        "Resource exhaustion (e.g., slowloris attack, excessive database queries)",
        "Account lockout/enumeration"
    ],
    "Elevation of Privilege": [
        "Unauthorized access to administrative functions",
        "Horizontal privilege escalation (accessing another user's data)"
    ]
}

for threat_type, threat_list in threats.items():
    print(f"   {threat_type}:")
    for threat in threat_list:
        print(f"     - {threat}")

# 5. Identify Vulnerabilities (examples based on identified threats)
print("\n5. Identified Vulnerabilities:")
vulnerabilities = [
    "Weak password policies or lack of password hashing",
    "Lack of HTTPS for client-server communication",
    "No input validation on user-provided data (e.g., SQL Injection, XSS)",
    "Improper session management (e.g., long-lived, predictable session tokens)",
    "Inadequate access controls (e.g., admin functions accessible to regular users)",
    "Default/weak database credentials",
    "Verbose error messages exposing system details"
]
for vuln in vulnerabilities:
    print(f"   - {vuln}")

# 6. Determine Countermeasures
print("\n6. Determined Countermeasures:")
countermeasures = [
    "Implement strong password policies and `bcrypt` for password hashing and storage.",
    "Enforce HTTPS/TLS for all client-server communication.",
    "Implement robust input validation and output encoding to prevent injection attacks (e.g., SQLi, XSS).",
    "Use secure, short-lived, and randomized session tokens with proper invalidation mechanisms.",
    "Implement Role-Based Access Control (RBAC) to enforce granular permissions.",
    "Use secure secret management for database credentials and other sensitive keys.",
    "Implement rate limiting for login attempts and API endpoints to mitigate DoS.",
    "Log and monitor security events (e.g., failed logins, access violations).",
    "Regular security audits and penetration testing."
]
for countermeasure in countermeasures:
    print(f"   - {countermeasure}")

print("\n--- Simple Web Application Threat Model Complete ---")
print("This exercise highlights the importance of systematically thinking about potential security risks at various layers of an application.")

"""### 1. Input Validation: Preventing Command Injection

We previously saw how `subprocess.call(f'echo {command}', shell=True)` was vulnerable to command injection. Input validation can help mitigate this by ensuring the `command` input is safe. For instance, we can validate that the input contains only allowed characters or matches a specific pattern.
"""

import re
import subprocess

def execute_safe_command_with_validation(user_input):
    # Example: Only allow alphanumeric characters, spaces, hyphens, dots, and underscores
    # This is a very restrictive example; real-world validation would be more complex.
    if not re.fullmatch(r'^[a-zA-Z0-9 _.-]+$', user_input):
        print(f"Validation failed: Invalid characters in input '{user_input}'.")
        return

    print(f"Executing validated command: 'ls -la {user_input}'")
    try:
        # Still use a safer subprocess execution method (list of arguments, no shell=True)
        result = subprocess.run(['ls', '-la', user_input], capture_output=True, text=True, check=True)
        print("Command output:\n", result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"Command execution failed: {e.stderr}")
    except FileNotFoundError:
        print(f"Command 'ls' or file '{user_input}' not found.")

print("--- Valid input example ---")
execute_safe_command_with_validation("vulnerable_app.py")

print("\n--- Malicious input example ---")
execute_safe_command_with_validation("vulnerable_app.py; rm -rf /; echo evil")

print("\n--- Another malicious input example ---")
execute_safe_command_with_validation("foo && cat /etc/passwd")

"""### 2. Output Encoding: Preventing Cross-Site Scripting (XSS)

**Output encoding** is the practice of converting user-supplied input into a safe form before it is rendered in an HTML page or other context. This ensures that the browser interprets the input as data rather than executable code.

Let's consider a simple web application scenario where user input is displayed back on a page. If the input is not encoded, a malicious script could be injected, leading to a Cross-Site Scripting (XSS) attack.
"""

from html import escape

def display_user_comment_vulnerable(comment):
    # Simulate rendering user input directly into an HTML context
    html_output = f"<div>User Comment: {comment}</div>"
    print(f"Vulnerable Output: {html_output}")

def display_user_comment_safe(comment):
    # Use html.escape to encode special HTML characters
    encoded_comment = escape(comment)
    html_output = f"<div>User Comment: {encoded_comment}</div>"
    print(f"Safe Output: {html_output}")


# --- Vulnerable Example ---
print("--- Vulnerable XSS Scenario ---")
malicious_comment = "<script>alert('XSS Attack!');</script>"
display_user_comment_vulnerable(malicious_comment)

# --- Safe Example ---
print("\n--- Safe XSS Scenario (Output Encoded) ---")
display_user_comment_safe(malicious_comment)

# Example with regular text
print("\n--- Regular Text Example ---")
display_user_comment_safe("Hello, this is a normal comment!")

"""## Security Testing: Unit Testing for Security

**Unit testing** is a software testing method where individual units or components of a software are tested. In a security context, unit tests can be written to verify that security-sensitive functions behave as expected, especially when faced with malicious or unexpected input.

We will write unit tests for the `execute_safe_command_with_validation` function we defined earlier, ensuring it correctly prevents command injection.
"""

import unittest
import io
import sys
import re
import subprocess

# Redefine the function here or ensure it's accessible from previous cells.
# For demonstration, we'll redefine it to make the test self-contained.
def execute_safe_command_with_validation(user_input):
    # Example: Only allow alphanumeric characters, spaces, hyphens, dots, and underscores
    if not re.fullmatch(r'^[a-zA-Z0-9 _.-]+$', user_input):
        print(f"Validation failed: Invalid characters in input '{user_input}'.")
        return

    # Added flush=True to ensure the output is immediately written to stdout and captured by the mock.
    print(f"Executing validated command: 'ls -la {user_input}'", flush=True)
    try:
        # Using a safer subprocess execution method (list of arguments, no shell=True)
        # For testing, we capture output and don't check=True for expected failures.
        # We are only checking if our validation logic prevents reaching this point.
        result = subprocess.run(['ls', '-la', user_input], capture_output=True, text=True, check=True)
        return {"status": "success", "stdout": result.stdout}
    except subprocess.CalledProcessError as e:
        return {"status": "command_failed", "stderr": e.stderr}
    except FileNotFoundError:
        return {"status": "file_not_found", "error": f"Command 'ls' or file '{user_input}' not found."}


class TestCommandInjectionPrevention(unittest.TestCase):

    def setUp(self):
        # Redirect stdout to capture print statements from the function
        self.held_stdout = sys.stdout
        self.mock_stdout = io.StringIO()
        sys.stdout = self.mock_stdout

    def tearDown(self):
        # Restore stdout
        sys.stdout = self.held_stdout

    def test_valid_input(self):
        # Test with a known good input
        # Ensure 'vulnerable_app.py' exists for this test to pass without 'file_not_found'
        result = execute_safe_command_with_validation("vulnerable_app.py")
        output = self.mock_stdout.getvalue()
        self.assertIn("Executing validated command", output)
        self.assertEqual(result['status'], 'success')
        self.assertIn("vulnerable_app.py", result['stdout'])

    def test_malicious_input_command_injection(self):
        # Test with malicious characters that should be blocked by validation
        malicious_input = "vulnerable_app.py; rm -rf /; echo evil"
        result = execute_safe_command_with_validation(malicious_input)
        output = self.mock_stdout.getvalue()
        self.assertIn("Validation failed: Invalid characters in input", output)
        # Assert that the subprocess command was not even attempted for this input
        self.assertNotIn("Executing validated command", output)
        self.assertIsNone(result)

    def test_malicious_input_cat_passwd(self):
        # Test another malicious input pattern
        malicious_input = "foo && cat /etc/passwd"
        result = execute_safe_command_with_validation(malicious_input)
        output = self.mock_stdout.getvalue()
        self.assertIn("Validation failed: Invalid characters in input", output)
        self.assertNotIn("Executing validated command", output)
        self.assertIsNone(result)

    def test_input_with_disallowed_characters(self):
        # Test input with characters not in the regex but not necessarily 'malicious'
        disallowed_input = "my_file!name.py"
        result = execute_safe_command_with_validation(disallowed_input)
        output = self.mock_stdout.getvalue()
        self.assertIn("Validation failed: Invalid characters in input", output)
        self.assertNotIn("Executing validated command", output)
        self.assertIsNone(result)


print("Running unit tests for command injection prevention...")
# Run the tests
suite = unittest.TestSuite()
suite.addTest(unittest.makeSuite(TestCommandInjectionPrevention))

# Use TextTestRunner to run the tests and display results
runner = unittest.TextTestRunner(stream=sys.stdout)
runner.run(suite)

"""## CI/CD Integration: Automating Security Scans

Integrating security tools into your Continuous Integration/Continuous Deployment (CI/CD) pipeline is crucial for identifying and remediating vulnerabilities early in the development lifecycle. This practice is often referred to as "shifting left" in security.

In a typical CI/CD pipeline, security scans can be automated at various stages:

1.  **Pre-commit/Pre-push Hooks**: Run fast static analysis locally before code is even committed or pushed.
2.  **Build Stage**: Automatically trigger static application security testing (SAST), dependency scanning, and secret scanning when new code is pushed to the repository.
3.  **Test Stage**: Include security-focused unit tests, integration tests, and potentially dynamic application security testing (DAST) against a deployed test environment.
4.  **Deployment Stage**: Scan container images for vulnerabilities before they are deployed to production.

Here, we'll simulate how some of the tools we've used (Bandit for SAST and `pip-audit` for dependency scanning) could be run as part of a simplified CI/CD process.

### 1. Simulate CI/CD Step: Static Code Analysis (Bandit)
"""

import subprocess
import json
import os

def run_bandit_scan_ci(file_to_scan, min_severity='medium', min_confidence='medium'):
    print(f"\n--- CI/CD Step: Running Bandit Scan on {file_to_scan} ---")
    print(f"Minimum Severity: {min_severity}, Minimum Confidence: {min_confidence}")

    bandit_command = [
        'bandit',
        '-r',
        file_to_scan,
        '-f', 'json',
        '-q',
        '--severity-level', min_severity,
        '--confidence-level', min_confidence
    ]

    try:
        result = subprocess.run(
            bandit_command,
            capture_output=True,
            text=True,
            check=False # Allow non-zero exit code if vulnerabilities are found
        )

        if result.stderr:
            print("Bandit Errors (stderr):")
            print(result.stderr)

        scan_data = json.loads(result.stdout)
        if scan_data and 'results' in scan_data and scan_data['results']:
            print(f"*** Bandit found {len(scan_data['results'])} security issues! ***")
            for finding in scan_data['results']:
                print(f"  [FAIL] Issue: {finding['issue_text']} (Severity: {finding['issue_severity']}, Confidence: {finding['issue_confidence']})")
                print(f"         File: {finding['filename']}, Line: {finding['line_number']}")
            return False # Indicate scan failure
        else:
            print("Bandit scan passed: No security issues found matching criteria.")
            return True # Indicate scan success
    except json.JSONDecodeError:
        print("Error decoding JSON output from Bandit.")
        print(f"Raw output: {result.stdout}")
        return False
    except Exception as e:
        print(f"An error occurred during Bandit scan: {e}")
        return False

# Run Bandit on our vulnerable application
bandit_passed = run_bandit_scan_ci(file_name, min_severity='low', min_confidence='low')

print(f"\nBandit CI/CD Step {'PASSED' if bandit_passed else 'FAILED'}.")

"""### 2. Simulate CI/CD Step: Dependency Scanning (`pip-audit`)"""

import subprocess
import json

def run_pip_audit_ci():
    print("\n--- CI/CD Step: Running pip-audit for Dependency Vulnerabilities ---")

    try:
        pip_audit_command = ['pip-audit', '--format', 'json']
        audit_result = subprocess.run(
            pip_audit_command,
            capture_output=True,
            text=True,
            check=False
        )

        if audit_result.stderr:
            print("pip-audit Errors (stderr):")
            print(audit_result.stderr)

        audit_data = json.loads(audit_result.stdout)
        vulnerable_packages_found = 0
        if 'dependencies' in audit_data:
            for dep_info in audit_data['dependencies']:
                if 'vulns' in dep_info and isinstance(dep_info['vulns'], list) and dep_info['vulns']:
                    vulnerable_packages_found += 1
                    package_name = dep_info.get('name', 'Unknown')
                    package_version = dep_info.get('version', 'Unknown')
                    print(f"  [FAIL] Vulnerable Package: {package_name}=={package_version}")
                    for vuln in dep_info['vulns']:
                        if isinstance(vuln, dict):
                            print(f"         Vulnerability ID: {vuln.get('id', 'N/A')}")
                            print(f"         Description: {vuln.get('details', 'No description available')[:100]}...")
                            if 'fix_versions' in vuln and vuln['fix_versions']:
                                print(f"         Fix versions: {', '.join(vuln['fix_versions'])}")

        if vulnerable_packages_found > 0:
            print(f"*** pip-audit found {vulnerable_packages_found} vulnerable packages! ***")
            return False # Indicate scan failure
        else:
            print("pip-audit scan passed: No vulnerable dependencies found.")
            return True # Indicate scan success

    except json.JSONDecodeError:
        print("Error decoding JSON output from pip-audit.")
        print(f"Raw output: {audit_result.stdout}")
        return False
    except Exception as e:
        print(f"An error occurred during pip-audit scan: {e}")
        return False

# Run pip-audit for installed dependencies
pip_audit_passed = run_pip_audit_ci()

print(f"\npip-audit CI/CD Step {'PASSED' if pip_audit_passed else 'FAILED'}.")

pip_audit_passed = run_pip_audit_ci()
print(f"\npip-audit CI/CD Step {'PASSED' if pip_audit_passed else 'FAILED'}.")

print("\n--- Simulating Full CI/CD Security Gate ---")

# Assuming 'file_name' is still 'vulnerable_app.py'
# And dependencies are installed from 'requirements.txt'

all_checks_passed = True

# Step 1: Static Code Analysis
if not run_bandit_scan_ci(file_name, min_severity='medium', min_confidence='medium'):
    all_checks_passed = False
    print("!!! CI/CD Security Gate: Static Code Analysis FAILED !!!")

# Step 2: Dependency Scanning
if not run_pip_audit_ci():
    all_checks_passed = False
    print("!!! CI/CD Security Gate: Dependency Scan FAILED !!!")


if all_checks_passed:
    print("\n--- CI/CD Security Gate: ALL CHECKS PASSED. Proceeding to next stage. ---")
else:
    print("\n--- CI/CD Security Gate: FAILED. Blocking build/deployment. ---")

"""### 3. Combining CI/CD Checks"""

print("\n--- Simulating Full CI/CD Security Gate ---")

# Assuming 'file_name' is still 'vulnerable_app.py'
# And dependencies are installed from 'requirements.txt'

all_checks_passed = True

# Step 1: Static Code Analysis
if not run_bandit_scan_ci(file_name, min_severity='medium', min_confidence='medium'):
    all_checks_passed = False
    print("!!! CI/CD Security Gate: Static Code Analysis FAILED !!!")

# Step 2: Dependency Scanning
if not run_pip_audit_ci():
    all_checks_passed = False
    print("!!! CI/CD Security Gate: Dependency Scan FAILED !!!")


if all_checks_passed:
    print("\n--- CI/CD Security Gate: ALL CHECKS PASSED. Proceeding to next stage. ---")
else:
    print("\n--- CI/CD Security Gate: FAILED. Blocking build/deployment. ---")

"""## Authentication and Authorization

**Authentication** is the process of verifying who a user is, while **Authorization** determines what an authenticated user is allowed to do. These are fundamental pillars of application security.

In this section, we will explore basic implementations of both concepts.

### 1. Basic Authentication: Username and Password

Let's start with a very basic example of user authentication using a hardcoded username and password. **Note:** This is purely for demonstration purposes to illustrate the concept. In a real-world application, credentials would be stored securely (e.g., hashed passwords in a database) and verified against a robust identity provider.
"""

def authenticate_user(username, password):
    # In a real application, passwords would be hashed and compared securely.
    # This is a simplified example for demonstration.
    VALID_USERS = {
        "admin": "secure_admin_pass",
        "user": "secure_user_pass"
    }

    if username in VALID_USERS and VALID_USERS[username] == password:
        print(f"Authentication successful for user: {username}")
        return True
    else:
        print(f"Authentication failed for user: {username}")
        return False

# --- Test Cases ---
print("\n--- Testing Authentication ---")
authenticate_user("admin", "secure_admin_pass") # Should pass
authenticate_user("user", "secure_user_pass")   # Should pass
authenticate_user("admin", "wrong_password")   # Should fail
authenticate_user("guest", "any_password")     # Should fail (unknown user)

"""### 2. Advanced Authentication: Password Hashing with `bcrypt`

Storing passwords in plain text, even in the simplified `authenticate_user` function, is a severe security risk. If a database is compromised, all user passwords would be exposed.

**Password Hashing** converts a password into a fixed-size string of characters using a one-way cryptographic function. A good hashing algorithm also incorporates a 'salt' (a random string) to prevent rainbow table attacks, and is computationally intensive to slow down brute-force attacks.

We will use the `bcrypt` library, a robust password-hashing function designed to be resilient against modern attacks.
"""

# Commented out IPython magic to ensure Python compatibility.
# Install bcrypt library
# %pip install bcrypt

import bcrypt

def hash_password(password):
    # Generate a salt and hash the password
    # bcrypt.gensalt() generates a random salt. The work factor (e.g., 12) determines how CPU-intensive the hashing is.
    # Higher work factors are more secure but slower.
    hashed_bytes = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt(rounds=12))
    return hashed_bytes.decode('utf-8') # Store as a UTF-8 string

def verify_password(plain_password, hashed_password):
    # Verify a plain password against a stored hash
    # bcrypt.checkpw automatically extracts the salt from the hashed_password
    return bcrypt.checkpw(plain_password.encode('utf-8'), hashed_password.encode('utf-8'))

# --- Demonstration ---
print("\n--- Demonstrating Password Hashing ---")

# Simulate user registration: hash the password
user_password = "MySuperSecurePassword123!"
hashed_user_password = hash_password(user_password)
print(f"Original password: {user_password}")
print(f"Hashed password (stored in DB): {hashed_user_password}")

# Simulate user login: verify the password
print("\n--- Simulating Login ---")

# Correct password
if verify_password(user_password, hashed_user_password):
    print("Login successful: Passwords match.")
else:
    print("Login failed: Passwords do NOT match.")

# Incorrect password
wrong_password = "WrongPassword123"
if verify_password(wrong_password, hashed_user_password):
    print("Login successful: Passwords match.")
else:
    print("Login failed: Incorrect password provided.")

# Try to re-hash the same password to show different hash (due to salt)
print("\n--- Re-hashing same password to show different output (due to salt) ---")
rehashed_same_password = hash_password(user_password)
print(f"Re-hashed '{user_password}': {rehashed_same_password}")
if rehashed_same_password == hashed_user_password:
    print("Hashes are the same (this should NOT happen).")
else:
    print("Hashes are different, as expected (due to unique salt).")

"""### 3. Introduction to Multi-Factor Authentication (MFA) and other advanced techniques

While password hashing significantly improves security, modern applications often require even stronger authentication mechanisms. This is where **Multi-Factor Authentication (MFA)** comes in.

MFA requires users to provide two or more verification factors to gain access to an application. These factors typically fall into three categories:

1.  **Something you know** (e.g., a password, a PIN)
2.  **Something you have** (e.g., a hardware token, a smartphone with an authenticator app)
3.  **Something you are** (e.g., a fingerprint, facial recognition)

Common MFA methods include:
*   **TOTP (Time-based One-Time Passwords)**: Like Google Authenticator or Authy, where a new code is generated every 30-60 seconds.
*   **SMS/Email Passcodes**: A code sent to a registered phone number or email address.
*   **Biometrics**: Fingerprint or face ID.
*   **Physical Security Keys**: USB-based keys like YubiKey.

**Other advanced authentication techniques often used in modern applications include:**

*   **OAuth 2.0 and OpenID Connect (OIDC)**: Protocols for delegated authorization and identity verification, commonly used for "Login with Google/Facebook" features.
*   **SSO (Single Sign-On)**: Allows a user to log in once and gain access to multiple related but independent software systems.
*   **Session Management**: Securely managing user sessions after authentication, including practices like short-lived tokens, token rotation, and invalidation upon logout or inactivity.

Implementing these techniques typically involves integrating with dedicated identity providers (IdPs) or authentication services rather than building them from scratch.

### 4. Authorization: Role-Based Access Control (RBAC)

Now that we can securely authenticate users, the next step is to control what those authenticated users are allowed to do. This is **Authorization**. A common model for authorization is **Role-Based Access Control (RBAC)**, where permissions are granted to roles, and roles are assigned to users.

Let's extend our authentication example to include a simple authorization check based on roles.
"""

import bcrypt

# Re-using our password hashing functions
def hash_password(password):
    hashed_bytes = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt(rounds=12))
    return hashed_bytes.decode('utf-8')

def verify_password(plain_password, hashed_password):
    return bcrypt.checkpw(plain_password.encode('utf-8'), hashed_password.encode('utf-8'))


# --- User Database with Hashed Passwords and Roles ---
# In a real system, this would be a database.
USER_DATABASE = {
    "admin_user": {
        "hashed_password": hash_password("AdminSecurePass123!"),
        "roles": ["admin", "editor", "viewer"]
    },
    "editor_user": {
        "hashed_password": hash_password("EditorPass456"),
        "roles": ["editor", "viewer"]
    },
    "viewer_user": {
        "hashed_password": hash_password("ViewerPass789"),
        "roles": ["viewer"]
    }
}

def authenticate_user_with_roles(username, password):
    user_info = USER_DATABASE.get(username)
    if user_info and verify_password(password, user_info["hashed_password"]):
        print(f"Authentication successful for user: {username}")
        return {"username": username, "roles": user_info["roles"]}
    else:
        print(f"Authentication failed for user: {username}")
        return None

def authorize_action(user_context, required_role):
    if not user_context:
        print("Authorization denied: User not authenticated.")
        return False

    if required_role in user_context["roles"]:
        print(f"Authorization granted for {user_context['username']} to perform action requiring '{required_role}'.")
        return True
    else:
        print(f"Authorization denied for {user_context['username']}: Missing required role '{required_role}'.")
        return False

# --- Demonstration ---
print("\n--- Demonstrating Authentication and Authorization ---")

# Authenticate different users
admin_context = authenticate_user_with_roles("admin_user", "AdminSecurePass123!")
editor_context = authenticate_user_with_roles("editor_user", "EditorPass456")
viewer_context = authenticate_user_with_roles("viewer_user", "ViewerPass789")
invalid_context = authenticate_user_with_roles("unknown_user", "any_password")

print("\n--- Testing Authorization for Admin Actions ---")
authorize_action(admin_context, "admin") # Should pass
authorize_action(editor_context, "admin") # Should fail
authorize_action(viewer_context, "admin") # Should fail

print("\n--- Testing Authorization for Editor Actions ---")
authorize_action(admin_context, "editor") # Should pass
authorize_action(editor_context, "editor") # Should pass
authorize_action(viewer_context, "editor") # Should fail

print("\n--- Testing Authorization for Viewer Actions ---")
authorize_action(admin_context, "viewer") # Should pass
authorize_action(editor_context, "viewer") # Should pass
authorize_action(viewer_context, "viewer") # Should pass

print("\n--- Testing Authorization for Unauthenticated User ---")
authorize_action(invalid_context, "viewer") # Should fail

print("\nThis example demonstrates how roles can be used to control access to different functionalities within an application.")

"""## Data Security: Encryption, Anonymization, and Privacy by Design

**Data Security** encompasses the measures and safeguards used to protect data from unauthorized access, corruption, or theft throughout its entire lifecycle. This includes ensuring data confidentiality, integrity, and availability.

Key aspects of data security include:
*   **Encryption**: Transforming data into a coded format to prevent unauthorized access.
*   **Data Anonymization**: Techniques to remove or modify personally identifiable information (PII) from data so that the data subject cannot be identified.
*   **Privacy by Design**: Embedding privacy considerations into the design and operation of information systems, rather than as an afterthought.

Let's begin by exploring **Encryption at Rest**.

### 1. Encryption at Rest: Protecting Stored Data

**Encryption at Rest** refers to the encryption of data when it is stored on any persistent storage medium (e.g., hard drives, databases, cloud storage). If an attacker gains access to the storage, the data remains unintelligible without the encryption key.

We will demonstrate symmetric encryption using the `cryptography` library's `Fernet` module, which provides a high-level API for encrypting and decrypting data using AES in CBC mode with a 128-bit key, as well as HMAC for authenticity.
"""

# Commented out IPython magic to ensure Python compatibility.
# Install the cryptography library
# %pip install cryptography

from cryptography.fernet import Fernet
import os

# --- Generate a Key ---
# In a real application, this key would be securely generated and stored,
# and not hardcoded or left in the codebase.
# It might be fetched from a secure key management system.
encryption_key = Fernet.generate_key()
fernet = Fernet(encryption_key)

print("Encryption key generated (keep this secret!):", encryption_key.decode())

# --- Data to Encrypt ---
original_data = b"This is very sensitive information that needs to be encrypted!"
print(f"\nOriginal data: {original_data.decode()}")

# --- Encrypt the Data ---
encrypted_data = fernet.encrypt(original_data)
print(f"Encrypted data: {encrypted_data.decode()}")

# --- Store Encrypted Data to a File ---
encrypted_file_name = "sensitive_data.enc"
with open(encrypted_file_name, "wb") as f:
    f.write(encrypted_data)
print(f"Encrypted data written to '{encrypted_file_name}'.")

# --- Simulate Reading Encrypted Data from File ---
with open(encrypted_file_name, "rb") as f:
    read_encrypted_data = f.read()

# --- Decrypt the Data ---
decrypted_data = fernet.decrypt(read_encrypted_data)
print(f"\nDecrypted data: {decrypted_data.decode()}")

# --- Verify Integrity (Fernet does this automatically) ---
# If the encrypted data is tampered with, or a wrong key is used, Fernet.decrypt() will raise an exception.
print("Data integrity verified by Fernet during decryption.")

# --- Clean up (optional) ---
os.remove(encrypted_file_name)
print(f"Cleaned up encrypted file '{encrypted_file_name}'.")

"""### 2. Encryption in Transit: Securing Data in Motion

**Encryption in Transit** (also known as encryption in motion) protects data as it moves from one point to another, typically over a network. This prevents eavesdropping and tampering by unauthorized parties during transmission.

The most common example of encryption in transit is **HTTPS** (Hypertext Transfer Protocol Secure), which uses **SSL/TLS** (Secure Sockets Layer/Transport Layer Security) to encrypt communication between a web browser and a server.

SSL/TLS works by establishing a secure channel between two communicating parties, ensuring:
*   **Confidentiality**: Data is encrypted, so only the intended recipient can read it.
*   **Integrity**: Data cannot be modified without detection.
*   **Authentication**: Parties can verify each other's identity.

Let's simulate a very basic secure communication using Python's `http.server` with SSL/TLS.

#### Generating Self-Signed SSL/TLS Certificates

For this demonstration, we'll need SSL/TLS certificates. In a real-world scenario, you would obtain these from a Certificate Authority (CA) like Let's Encrypt. For local testing, we can generate a self-signed certificate.

We'll use `openssl` to create a private key and a self-signed certificate. **Note:** Self-signed certificates are *not* trusted by browsers or other clients by default and will cause security warnings. They are suitable for local development and demonstration only.
"""

import subprocess
import os

# Define certificate and key file names
cert_file = "server.crt"
key_file = "server.key"

# Check if files already exist to avoid regenerating
if not os.path.exists(cert_file) or not os.path.exists(key_file):
    print("Generating self-signed SSL/TLS certificate and private key...")
    try:
        # Generate a private key (2048-bit RSA)
        subprocess.run(
            ['openssl', 'genrsa', '-out', key_file, '2048'],
            check=True, capture_output=True, text=True
        )
        # Generate a self-signed certificate
        # -x509: output a self-signed certificate
        # -nodes: no DES encryption of the private key
        # -days 365: certificate valid for 365 days
        # -new: generate a new certificate request
        # -key: use this key
        # -out: output certificate file
        # -subj: subject information (common name CN is important for hostname matching)
        subprocess.run(
            ['openssl', 'req', '-new', '-x509', '-nodes', '-days', '365',
             '-key', key_file, '-out', cert_file, '-subj', '/CN=localhost'],
            check=True, capture_output=True, text=True
        )
        print(f"Successfully generated '{key_file}' and '{cert_file}'.")
    except subprocess.CalledProcessError as e:
        print(f"Error generating certificates: {e.stderr}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
else:
    print(f"SSL/TLS certificate '{cert_file}' and key '{key_file}' already exist.")

# Verify files are present
print(f"Checking for '{key_file}': {os.path.exists(key_file)}")
print(f"Checking for '{cert_file}': {os.path.exists(cert_file)}")

"""#### Implementing a Simple HTTPS Server and Client

Now, let's create a minimal HTTPS server and a client to demonstrate secure communication. Since we are in a Colab environment and need to demonstrate both server and client, we'll run the server in a separate thread and have the client connect to it.
"""

import http.server
import ssl
import threading
import time
import urllib.request

# Configuration
HTTPS_PORT = 8443 # Standard HTTPS port
CERT_FILE = "server.crt"
KEY_FILE = "server.key"

# --- HTTPS Server Class ---
class SecureHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()
        response_message = f"Hello from the secure server! You accessed {self.path} over HTTPS."
        self.wfile.write(response_message.encode('utf-8'))

    def log_message(self, format, *args):
        # Suppress logging to avoid cluttering output when running in thread
        pass

def run_https_server():
    try:
        httpd = http.server.HTTPServer(('localhost', HTTPS_PORT), SecureHandler)

        # Create an SSL context
        ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
        ssl_context.load_cert_chain(certfile=CERT_FILE, keyfile=KEY_FILE)

        # Wrap the socket with the SSL context
        httpd.socket = ssl_context.wrap_socket(
            httpd.socket,
            server_side=True
        )
        print(f"Secure HTTPS server started on https://localhost:{HTTPS_PORT}/")
        httpd.serve_forever()
    except FileNotFoundError:
        print("Error: Certificate or key file not found. Please run the previous cell to generate them.")
    except Exception as e:
        print(f"Error running HTTPS server: {e}")
    finally:
        print("HTTPS server stopped.")

# --- Client Request Function ---
def make_secure_request():
    url = f"https://localhost:{HTTPS_PORT}/secure-resource"
    print(f"\nAttempting to make a secure request to {url}...")
    try:
        # For self-signed certificates, we must disable SSL verification in the client.
        # In a real application with trusted CAs, you would NOT do this.
        context = ssl._create_unverified_context()
        with urllib.request.urlopen(url, context=context) as response:
            print("Secure Client Response:")
            print(response.read().decode('utf-8'))
    except urllib.error.URLError as e:
        print(f"Client request failed: {e.reason}")
    except ConnectionRefusedError:
        print("Client request failed: Connection refused. Is the server running?")
    except Exception as e:
        print(f"An unexpected error occurred during client request: {e}")

# --- Main Execution ---
print("--- Demonstrating Encryption in Transit (HTTPS) ---")

# Run server in a separate thread
server_thread = threading.Thread(target=run_https_server)
server_thread.daemon = True # Allow main program to exit even if server thread is running
server_thread.start()

# Give the server a moment to start up
time.sleep(2)

# Make the client request
make_secure_request()

print("\n--- HTTPS Demonstration Complete ---")
# Note: In a real notebook, you might need to manually stop the server thread
# or allow it to terminate naturally with the notebook runtime.